name: Sync customer requests

on:
  issues:
    types: [opened, edited]

jobs:
  prepare:
    name: Prepare
    runs-on:  ubuntu-latest

    if: github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'edited')

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: $
        run: echo "$GITHUB_CONTEXT"

      - name: Post prepare message
        uses: actions/github-script@v5
        with:
          script: |
             const options = { myVariable: '$' }
             await require('./.github/scripts/prepare.js')({github, context, options})
      - if: $
        name: Report failed migration
        uses: actions/github-script@v3
        with:
          script: |
            const body = `:no_entry: **Prepare step failed.** [View workflow run for details](${context.payload.repository.html_url}/actions/runs/${context.runId})`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })
