name: Sync customer requests

on:
  issues:
    types: [opened, edited]

jobs:
  prepare:
    name: Prepare
    runs-on:  ubuntu-latest

    if: github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'labeled')

    steps:
      - name: Dumps
        run: |
          apt install jq
          echo ------
          echo ${{ github.event }} | jq .
#      - name: Post prepare message
#        uses: actions/github-script@v5
#        with:
#          script: |
#             const options = { myVariable: '$' }
#             await require('./.github/scripts/prepare.js')({github, context, options})
